### ISSUE TITLE
Feature request: Lifecycle

### ISSUE THREAD

**Issue by Nicolab** [hkalexling/mg#1]
Hello,

Thanks for this useful shards. The fact of managing migrations in Crystal code instead of raw SQL files allows some possibilities (available with migration libs in other languages, but non-existent in Crystal).

Unless I am mistaken, MG only allows to do actions before the migration and at the end of all migrations of course (after `mg.migrate`).

In the idea to be able to program actions during migrations, it would be interesting to have (optional) lifecycle methods in each class.

Example:

```crystal
def up : String
   puts "before up.  Actually it's already possible"

  <<-SQL
    # SQL statements....
  SQL
end

def up_done
  puts "after up is done"
end

def down : String
   puts "before down.  Actually it's already possible"

  <<-SQL
    # SQL statements....
  SQL
end

def down_done
  puts "after down is done"
end
```

This can be useful to perform data conversions (due to a new DB structure by example), clean cache, ... Example for migrating entries linked by foreign keys, useful for the next migration.

Just a suggestion, this can be implemented by adding empty methods (example: `up_done` and `down_done`) in `MG::Base`. Then call them after `exec query` https://github.com/hkalexling/mg/blob/5320c19c588856ce0f9ec323607caa9f78f8dc7e/src/mg/migration.cr#L138

What do you think?

Also, I have another question by the way. Is it an occasional shard (no particular need for you) or are you planning to maintain it for a long time?

This (curious) question because I want to add MG here https://github.com/Nicolab/crystal-dbx/blob/master/guide/migration.md (DBX docs) as well as use it by default in a framework that I will release soon 🙂

**Comment by hkalexling** [comment]
Hey, thanks for reaching out! I think it's a great idea, and I will take a look when I have the time. If you are interested, feel free to submit a PR!

> Is it an occasional shard (no particular need for you) or are you planning to maintain it for a long time?

Yes, it will be actively maintained. I created this shard because I need it in https://github.com/hkalexling/Mango.

**Comment by Nicolab** [comment]
Great, good news :+1: 
- [x] <del>Find a cool migration tool</del>

I'll find a time in the week to send you a PR! :)

**Comment by hkalexling** [comment]
Great, looking forward to it! Let me know if you need any help 👍

**Comment by Nicolab** [comment]
I will, thanks!
