### ISSUE TITLE
ERROR:  syntax error at or near "PRAGMA" at character 1

### ISSUE THREAD

**Issue by Nicolab** [hkalexling/mg#2]
Hello,

Using `Tags` annotation with Posgres causes this SQL error:

```
STATEMENT:  PRAGMA user_version
ERROR:  syntax error at or near "PRAGMA" at character 1
```
Caused by https://github.com/hkalexling/mg/blob/master/src/mg/migration.cr#L83
Because PRAGMA is SQLite specific. 

```crystal
  @[MG::Tags("db1")]
  class CreateTables < MG::Base
```

When I remove `Tags`, the migrations are ok but the error is always here.
What is the use of Tags annotation?

**Comment by hkalexling** [comment]
Hmm, that's odd. We do have a rescue block following that line: https://github.com/hkalexling/mg/blob/a19417abf03eece80039f89569926cff1ce3a1a3/src/mg/migration.cr#L84-L90

So essentially, we try to use pragma first, and if it fails, we create a `mg_version` table to store the current version. I am not sure why using the `Tags` annotation would cause it to skip the rescue block. I will take a look.

The `Tags` annotation is documented here https://hkalexling.github.io/mg/MG/Tags.html

**Comment by hkalexling** [comment]
IIRC, I've tested this shard on MySQL and it does work. Never tested it with Postgres though. I should probably set up a GitHub action to automatically test on all common SQL DBs.

**Comment by Nicolab** [comment]
Thanks for your reply. 

Concerning the tags, there is no problem at all. I didn't understand the usage, I didn't provide it as an argument of `mg.migrate`. I have read the doc, it's ok now, thanks. It can be handy :)

With `pragma` it works but it executes an invalid query in the DB. I have sent a PR to avoid this by checking if the DB is SQLite instead of executing an invalid query.
