### ISSUE TITLE
lifecycle hooks don't seem to work

### ISSUE THREAD

**Issue by kingsleyh** [hkalexling/mg#5]
Hi

after_up and after_down don't seem to be executed when calling migrate. My puts statements there did not show up.

**Comment by kingsleyh** [comment]
hmm when cloned this project and ran the tests and  put a string from the after_up it did print during the spec run. It looks like the documentation is wrong and you need to pass a conn to the after_up or after_down like this:

```
def after_up(conn : DB::Connection)
end
```
if you don't pass this conn then the after_up is never executed.
Although the after_up is now executed it still does not write out the put statement - but I can see it does execute the other code in after_up at least.

**Comment by hkalexling** [comment]
Ah yes, the example code in README is indeed incorrect. I will update it soon. Thanks for the heads-up!

> Although the after_up is now executed it still does not write out the put statement - but I can see it does execute the other code in after_up at least.

I can't reproduce this. If the rest of the code works in the hook, the put statements should work as well. Could you show us a reproducible example?

**Comment by kingsleyh** [comment]
It's probably just in my project - in the specs the put is printed out - so I will investigate.
