### ISSUE TITLE
How to migrate 2 databases

### ISSUE THREAD

**Issue by kingsleyh** [hkalexling/mg#6]
Hi 

I have 2 sqlite3 databases - can this tool support migrating each of them? when I tried it gets confused saying duplicate versions found.

**Comment by hkalexling** [comment]
You can use the `MG::Tags` annotation documented here: https://hkalexling.github.io/mg/MG/Tags.html

**Comment by kingsleyh** [comment]
awesome thanks - this is a really awesome migration tool :) great job!
